services:
  - type: scheduled
    name: binance-job
    schedule: "0 0 * * *"
    startCommand: |
      R -e "install.packages(c('httr', 'jsonlite', 'dplyr'), repos='https://cloud.r-project.org')"
      Rscript binance.R
    envVars:
      - key: RENDER
        value: "true"
       
