services:
  - type: cron
    name: binance-cron
    plan: free
    buildCommand: |
      apt-get update -qq
      apt-get install -y --no-install-recommends r-base-core
    runCommand: Rscript /opt/render/project/src/binance.R
    envVars:
      - key: RENDER
        value: true
      - key: GITHUB_PAT
        value: your_github_token_here
