services:
  - type: cron
    name: binance-cron
    plan: free
    buildCommand: |
      apt-get update -qq && \
      apt-get install -y \
        r-base \
        libcurl4-openssl-dev \
        libssl-dev \
        libxml2-dev
    runCommand: Rscript /opt/render/project/src/binance.R
    envVars:
      - key: RENDER
        value: "true"
      - key: GITHUB_PAT
        value: "ghp_votre_token_ici"
