services:
  - type: cron
    name: binance-cron
    plan: free
    buildCommand: |
      apt-get update -qq
      apt-get install -y --no-install-recommends r-base-core
    runCommand: Rscript /opt/render/project/src/binance.R
    envVars:
      - key: RENDER
        value: "true"
      - key: GITHUB_PAT
        value: "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"
