services:
  - type: cron
    name: binance-updater
    plan: free
    runtime: docker
    dockerfilePath: Dockerfile
    schedule: "0 0 * * *"  # Exécution quotidienne à minuit UTC
    envVars:
      - key: RENDER
        value: "true"
      - key: GITHUB_PAT
        value: "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"
