services:
  - type: scheduled
    name: binance-updater
    plan: free
    dockerfilePath: Dockerfile
    schedule: "0 0 * * *"  # Minuit UTC chaque jour
    envVars:
      - key: RENDER
        value: "true"
      - key: GITHUB_PAT
        value: "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"
       
