services:
  - type: cron
    name: binance-cron
    schedule: "0 0 * * *"  # Tous les jours à minuit UTC
    buildCommand: |
      apt-get update -qq && \
      apt-get install -y --no-install-recommends \
        r-base \
        libcurl4-openssl-dev \
        libssl-dev \
        libxml2-dev
    startCommand: Rscript /opt/render/project/src/binance.R
    envVars:
      - key: RENDER
        value: "true"
      - key: GITHUB_PAT
        value: "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"
