name: Binance Data Update

on:
  schedule:
    - cron: '0 0 * * *'  # Minuit UTC chaque jour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.0'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcurl4-openssl-dev \
          libssl-dev \
          libxml2-dev
        R -e "install.packages(c('httr', 'jsonlite', 'dplyr', 'readr'), repos='https://cloud.r-project.org')"

    - name: Configure DNS
      run: |
        echo "185.199.108.133 api.scrapingbee.com" | sudo tee -a /etc/hosts
        echo "185.199.109.133 api.scrapingbee.com" | sudo tee -a /etc/hosts
        echo "185.199.110.133 api.scrapingbee.com" | sudo tee -a /etc/hosts
        echo "185.199.111.133 api.scrapingbee.com" | sudo tee -a /etc/hosts

    - name: Run script
      run: Rscript binance.R

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add *.csv
        git diff --cached --quiet || (git commit -m 'Auto-update data' && git push)
