name: Binance Data Update

on:
  schedule:
    - cron: '0 0 * * *'  # Minuit UTC chaque jour
  workflow_dispatch:    # Permet de déclencher manuellement

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libgit2-dev \
            libssh2-1-dev \
            libcurl4-gnutls-dev \
            build-essential

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("httr", "curl", "jsonlite", "dplyr", "readr"), repos = "https://cloud.r-project.org")'

      - name: (Optionnel) Fix accès à raw.githubusercontent.com
        run: |
          echo "185.199.108.133 raw.githubusercontent.com" | sudo tee -a /etc/hosts
          echo "185.199.109.133 raw.githubusercontent.com" | sudo tee -a /etc/hosts
          echo "185.199.110.133 raw.githubusercontent.com" | sudo tee -a /etc/hosts
          echo "185.199.111.133 raw.githubusercontent.com" | sudo tee -a /etc/hosts

      - name: Run data update script
        run: Rscript binance.R
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *.csv
          git commit -m "Auto-update data" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
