name: Binance Data Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.0'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcurl4-openssl-dev \
          libssl-dev \
          libxml2-dev

    - name: Install R packages
      run: |
        R -e "install.packages(c('httr', 'jsonlite', 'dplyr', 'readr' ,'tidyr'), repos='https://cloud.r-project.org')"
        R -e "if (!require('httr')) quit(status=1)"

    - name: Run script
      run: Rscript binance.R
      env:
           SCRAPINGBEE_API_KEY: ${{ secrets.SCRAPINGBEE_API_KEY }}

    - name: Commit changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add *.csv
        git commit -m "Auto-update data" || echo "No changes to commit"
        git push
