name: Binance Data Update

on:
  schedule:
    - cron: '15 0 * * *'   # chaque jour à minuit UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.0'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Install R packages
      run: |
        Rscript -e "install.packages(c('httr','jsonlite','dplyr','readr','tidyr'), repos='https://cloud.r-project.org')"

    - name: Run Binance script
      run: |
        Rscript binance.R
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

    - name: Commit & push CSVs
      if: success()
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add df_normal.csv df_whale.csv q_whale.csv
        git diff --quiet || git commit -m "Auto update data $(date -u +'%Y-%m-%d')"
        git push
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

    - name: Upload error log
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-log
        path: error_log.txt
