name: Run Binance Script Daily

on:
  schedule:
    - cron: '0 0 * * *'   # Tous les jours à minuit UTC
  workflow_dispatch:      # Permet aussi de lancer manuellement
  
jobs:
  run-binance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install required R packages
      run: |
        Rscript -e 'install.packages(c("httr", "jsonlite", "dplyr"))'

    - name: Run binance.R
      run: |
        Rscript binance.R

    - name: Commit and Push results
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add df_normal.csv df_whale.csv q_whale.csv
        git commit -m "Daily update $(date -u '+%Y-%m-%d %H:%M:%S')"
        git push

