name: Run Binance Script

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install required R packages
        run: |
          Rscript -e 'install.packages(c("httr", "jsonlite", "dplyr"), repos = "https://cloud.r-project.org", dependencies = TRUE)'

      - name: Run R script
        run: |
          Rscript binance.R

      - name: Commit updated CSV files
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions"
          git add *.csv
          git commit -m "Update CSVs from Binance API" || echo "No changes to commit"
          git push

